# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 718dacb6558f2c6df4282d96046da13bbf4434d33aa5f56dc610e784c56306480acf5a6e4045ff6acc033c5eb631c38bec730fbdfadb2fc633ba00bcc9f3c3a0

test:
  secret_key_base: 158895a846695c9f14ed2ab30a773c1c5f80b99519c6cbb77d36da48b192d84ae9c899ed1f24e40e57e679d352fd970e28457eda57bb578dfa1c3804b89c9477

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
